server.port=${PORT:5000}
spring.application.name=cli-auth-backend

# MongoDB Configuration
spring.data.mongodb.uri=${MONGODB_URI}

# Logging configuration
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.data.mongodb=DEBUG

# Disable Spring Security default login form
spring.security.user.name=admin
spring.security.user.password=admin
